### ISSUE TITLE
empty window  

### ISSUE THREAD

**Issue by sigmaharsh** [nwaliaez/ez-notes-app#1]
The project was being set up on my local machine without any errors but when i run
npm run dev
The electron window pops up which is empty and transparent 
![Screenshot_2024-11-14_22_48_48](https://github.com/user-attachments/assets/61c26124-917d-4344-aeb4-9a50e9fa3f53)

**Comment by nwaliaez** [comment]
I think you are not setting .env file mostly if thats also not the issue in main/index.ts file uncomment dev tools and you will be able to see the errors

**Comment by sigmaharsh** [comment]
Ok, I'll check it out.

**Comment by sigmaharsh** [comment]
Also earlier it showed errors with firebase that time the window opened with the inspect element tab I just did npm install firebase after that no errors were shown on the console as such

**Comment by nwaliaez** [comment]
Yes .env contains firebase keys you will have to add those

**Comment by sigmaharsh** [comment]
Got it ! thanks sir  will close this issue now
